---
title: "Publications"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
---

<style>
h1{margin-top: 36px}
</style>

<br>

# Refereed Journal Articles

---

## 2018

- **Coyner AS**, Swan R, Brown JM, Kalpathy- Cramer J, Kim SJ, Campbell JP, Jonas KE, Ostmo S, Chan RVP, Chiang MF. Deep Learning for Image Quality Assessment of Fundus Images in Retinopathy of Prematurity. AMIA Annual Symposium Proceedings. 2018. In press.

- [Ku CA, Ryals RC, Jiang D, **Coyner AS**, Weller KK, Sinha W, Robb BM, Yang P, Pennesi ME. The Role of ERK1/2 Activation in Sarpogrelate-Mediated Neuroprotection. Invest Ophthalmol Vis Sci. 2018;59(1):462-471.](https://www.ncbi.nlm.nih.gov/pubmed/29368005)

- [Al-Qahtani AA, Ba-Ali S, Alabduljalil T, **Coyner AS**, Patel RC, Weleber RG, Girach A, Christensen SK, Larsen M, Pennesi ME, Yang P. Scleral Pits in Choroideremia: Implications for Retinal Gene Therapy. Retina. 2018;38(9):1725-1730.](https://www.ncbi.nlm.nih.gov/pubmed/29160785)


## 2017

- [Ryals RC, Andrews MD, Datta S, **Coyner AS**, Fischer CM, Wen Y, Pennesi ME, McGill TJ. Long-term Characterization of Retinal Degeneration in Royal College of Surgeons Rats Using Spectral-Domain Optical Coherence Tomography. Invest Ophthalmol Vis Sci. 2017;58(3):1378-1386.](https://www.ncbi.nlm.nih.gov/pubmed/28253400)


## 2016

- [**Coyner AS**, Ryals RC, Ku CA,  Fischer CM, Patel RC, Datta S, Yang P, Wen Y, Hen R, Pennesi ME. Retinal Neuroprotective Effects of Flibanserin, an FDA-Approved Dual Serotonin Receptor Agonist-Antagonist. PLoS One. 2016;11(7):e0159776.](https://www.ncbi.nlm.nih.gov/pubmed/27447833)


## 2015

- [Tullis BE, Ryals RC, **Coyner AS**, Gale MJ, Nicholson A, Ku C, Regis D, Sinha W, Datta S, Wen Y, Yang P, Pennesi ME. Sarpogrelate, a 5-HT2A Receptor Antagonist, Protects the Retina From Light-Induced Retinopathy. Invest Ophthalmol Vis Sci. 2015;56(8):4560-4569.](https://www.ncbi.nlm.nih.gov/pubmed/26200496)


<br>

<br>

# Conference Posters

---

## 2018

- [**Coyner AS**, Swan R, Brown JM, Kalpathy-Cramer J, Kim SJ, Campbell JP, Jonas K, Chan RVP, Ostmo S, Chiang MF. Deep Learning for Image Quality Assessment of Fundus Images in Retinopathy of Prematurity. 2018 Association for Research in Vision and Ophthalmology Annual Conference. 2018; Honolulu, HI.](posters/arvo2018.pdf)
    + **Members-in-Training Outstanding Poster Award Finalist**
    
<br>

-  Yang P, Lockard RA, Titus H, Weller KK, **Coyner AS**, Duvoisin R, Weleber RG, Morgans C, Pennesi ME. Early Treatment with Mycophenolate Mofetil Reduces Retinal Degeneration and cGMP Dysregulation in rd10 and rd1 Mice. 2018 Association for Research in Vision and Ophthalmology Annual Conference. 2018; Honolulu, HI.


## 2017

- [**Coyner AS**, Swan R, Kalpathy-Cramer J, Kim SJ, Campbell JP, Jonas KE, Ostmo S, Chan RVP, Chiang MF. Automated Image Quality Assessment for Fundus Images in Retinopathy of Prematurity. 2017 American Medical Informatics Association Annual Symposium. 2017; Washington, DC.](posters/amia2017.pdf)

- [**Coyner AS**, Swan R, Kalpathy-Cramer J, Kim SJ, Campbell JP, Jonas KE, Ostmo S, Chan RVP, Chiang MF. Automated Image Quality Assessment for Fundus Images in Retinopathy of Prematurity. 2017 Association for Research in Vision and Ophthalmology Annual Conference. 2017; Baltimore, MD.](posters/arvo2017.pdf)


## 2016

- [**Coyner AS**, Ryals RC, Ku CA, Patel RC, Fischer C, Wen Y, Hen R, Pennesi ME. Flibanserin, an FDA-approved Dual Serotonin Receptor Agonist-antagonist, Provides Retinal Neuroprotection from Light Induced Damage. 2016 Association for Research in Vision and Ophthalmology Annual Conference. 2016; Seattle, WA.](posters/arvo2016.pdf)

- Ku CA, Ryals RC, Jiang D, **Coyner AS**, Weller KK, Sinha W, Robb BM, Yang P, Pennesi ME. The Role of ERK1/2 Activation in Serotonin-receptor Mediated Protection Against Light-induced Retinopathy. 2016 Association for Research in Vision and Ophthalmology Annual Conference. 2016; Seattle, WA.


## 2015

- Ryals RC, Datta S, **Coyner AS**, Gemechu H, Chu A, Wen Y, Pennesi ME. Potential of 5-HT3 Receptor Modulation for Protection of Light-induced Retinopathy. 2015 Association for Research in Vision and Ophthalmology Annual Conference. 2015; Denver, CO.

- Datta S, Ryals RC, **Coyner AS**, Pennesi ME. Cell signaling pathways involved in 8-OH-DPAT Dependent Neuroprotection. 2015 Association for Research in Vision and Ophthalmology Annual Conference. 2015; Denver, CO.